Imports

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
# import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.feature_selection import mutual_info_regression
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import OneHotEncoder
from xgboost import XGBRegressor

Data import

In [2]:
train = pd.read_csv("data/training.csv")
test = pd.read_csv("data/test.csv")




In [3]:
def make_mi_scores(X, y):
    X = X.copy()
    for colname in X.select_dtypes(["object", "category"]):
        X[colname], _ = X[colname].factorize()
    # All discrete features should now have integer dtypes
    discrete_features = [pd.api.types.is_integer_dtype(t) for t in X.dtypes]
    mi_scores = mutual_info_regression(X, y, discrete_features=discrete_features, random_state=0)
    mi_scores = pd.Series(mi_scores, name="MI Scores", index=X.columns)
    mi_scores = mi_scores.sort_values(ascending=False)
    return mi_scores

    # f1_scores = cross_val_score(XGBRegressor(), X, y, scoring="f1", cv=5)
    # f1_scores = pd.Series(f1_scores, name="F1 Scores")

Exploring dataSet

In [4]:

# train.select_dtypes(["object"]).nunique()
train.head(5)
# test.select_dtypes(["object"]).nunique()
# test.head()


TransactionId         BatchId       AccountId       SubscriptionId  \
0  TransactionId_76871   BatchId_36123  AccountId_3957   SubscriptionId_887   
1  TransactionId_73770   BatchId_15642  AccountId_4841  SubscriptionId_3829   
2  TransactionId_26203   BatchId_53941  AccountId_4229   SubscriptionId_222   
3    TransactionId_380  BatchId_102363   AccountId_648  SubscriptionId_2185   
4  TransactionId_28195   BatchId_38780  AccountId_4841  SubscriptionId_3829   

        CustomerId CurrencyCode  CountryCode    ProviderId     ProductId  \
0  CustomerId_4406          UGX          256  ProviderId_6  ProductId_10   
1  CustomerId_4406          UGX          256  ProviderId_4   ProductId_6   
2  CustomerId_4683          UGX          256  ProviderId_6   ProductId_1   
3   CustomerId_988          UGX          256  ProviderId_1  ProductId_21   
4   CustomerId_988          UGX          256  ProviderId_4   ProductId_6   

      ProductCategory    ChannelId   Amount  Value  TransactionStartTime  \
0             airtime  ChannelId_3   1000.0   1000  2018-11-15T02:18:49Z   
1  financial_services  ChannelId_2    -20.0     20  2018-11-15T02:19:08Z   
2             airtime  ChannelId_3    500.0    500  2018-11-15T02:44:21Z   
3        utility_bill  ChannelId_3  20000.0  21800  2018-11-15T03:32:55Z   
4  financial_services  ChannelId_2   -644.0    644  2018-11-15T03:34:21Z   

   PricingStrategy  FraudResult  
0                2            0  
1                2            0  
2                2            0  
3                2            0  
4                2            0

In [5]:
train.nunique()
# test.nunique()

TransactionId           95662
BatchId                 94809
AccountId                3633
SubscriptionId           3627
CustomerId               3742
CurrencyCode                1
CountryCode                 1
ProviderId                  6
ProductId                  23
ProductCategory             9
ChannelId                   4
Amount                   1676
Value                    1517
TransactionStartTime    94556
PricingStrategy             4
FraudResult                 2
dtype: int64

Feature encoding and engineering

In [6]:
train = train.sample(frac=1).reset_index(drop=True)
train_Y = train.FraudResult
train.drop(['FraudResult'], axis=1, inplace=True)



features = ["BatchId","AccountId","SubscriptionId","CustomerId","ProviderId","ProductId","ProductCategory","ChannelId","Amount","Value","TransactionStartTime","PricingStrategy"]

# train.drop(['CurrencyCode','CountryCode'], axis=1, inplace=True)
# test.drop(['CurrencyCode','CountryCode'], axis=1, inplace=True)


In [7]:
def getDay(x):
    return float(''.join(x.split("T")[0].split("-")))

def getTime(x):
    time = x.split("T")[1].split(":")
    time[-1] = time[-1][:-1]
    return float(''.join(time))

In [8]:
StringToClean = ["TransactionId", "BatchId","AccountId","SubscriptionId","CustomerId", "ProviderId", "ProductId", "ChannelId", "ProductCategory"]

# train[StringToClean].apply()

first_data = train.copy()
for col in StringToClean:
    test_data[col] = test_data[col].apply(lambda x : x.split("_")[-1])

first_data["TransactionStartDay"]  = first_data["TransactionStartTime"].apply(getDay)
first_data["TransactionStartTime"] = first_data["TransactionStartTime"].apply(getTime)
first_data = first_data.set_index("TransactionId")
first_data.drop(['CurrencyCode'], axis=1, inplace=True)
OH_encoder = OneHotEncoder(handle_unknown='ignore', sparse=False)
OH_cols_train = pd.DataFrame(OH_encoder.fit_transform(first_data["ProductCategory"].values.reshape(-1,1)))
OH_cols_train.rename(columns=lambda x: "ProductCategory_" + str(x), inplace=True)

# One-hot encoding removed index; put it back
OH_cols_train.index = first_data.index

# Remove categorical columns (will replace with one-hot encoding)
num_X_train = first_data.drop(["ProductCategory"], axis=1)

# Add one-hot encoded columns to numerical features
OH_X_train = pd.concat([num_X_train, OH_cols_train], axis=1)


OH_X_train.head()
# OH_X_train["TransactionStartTime"].head()


c:\Python310\lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


BatchId AccountId SubscriptionId CustomerId  CountryCode  \
TransactionId                                                            
73605           88193      4421           4038       4878          256   
99569           60799      3981            910       4431          256   
117572          83775      1457           1879       1825          256   
76642          120985       299           4090        627          256   
23026           61912      4840           3829       2782          256   

              ProviderId ProductId ChannelId    Amount   Value  ...  \
TransactionId                                                   ...   
73605                  5        15         3  300000.0  300000  ...   
99569                  5        15         3     900.0     900  ...   
117572                 6         3         3   10000.0   10000  ...   
76642                  6        10         3    1000.0    1000  ...   
23026                  4         6         2   -1000.0    1000  ...   

               TransactionStartDay  ProductCategory_0  ProductCategory_1  \
TransactionId                                                              
73605                   20181220.0                0.0                0.0   
99569                   20190120.0                0.0                0.0   
117572                  20181228.0                1.0                0.0   
76642                   20181222.0                1.0                0.0   
23026                   20181228.0                0.0                0.0   

               ProductCategory_2  ProductCategory_3  ProductCategory_4  \
TransactionId                                                            
73605                        0.0                0.0                0.0   
99569                        0.0                0.0                0.0   
117572                       0.0                0.0                0.0   
76642                        0.0                0.0                0.0   
23026                        0.0                0.0                0.0   

               ProductCategory_5  ProductCategory_6  ProductCategory_7  \
TransactionId                                                            
73605                        1.0                0.0                0.0   
99569                        1.0                0.0                0.0   
117572                       0.0                0.0                0.0   
76642                        0.0                0.0                0.0   
23026                        1.0                0.0                0.0   

               ProductCategory_8  
TransactionId                     
73605                        0.0  
99569                        0.0  
117572                       0.0  
76642                        0.0  
23026                        0.0  

[5 rows x 22 columns]

creating different models


In [9]:
decisionTree = DecisionTreeClassifier()

randomForest = RandomForestClassifier()

multiLayerPerceptron = MLPClassifier()

# decisionTree.fit(OH_X_train, train_Y)

# randomForest.fit(OH_X_train,train_Y)

# multiLayerPerceptron.fit(OH_X_train, train_Y)


In [10]:
f1_scores_mlp = cross_val_score(multiLayerPerceptron, OH_X_train, train_Y, scoring="f1", cv=5)
print(f1_scores_mlp)

[0.49253731 0.8        0.72463768 0.48648649 0.58181818]


In [11]:
f1_scores_DT = cross_val_score(decisionTree, OH_X_train, train_Y, scoring="f1", cv=5)
print(f1_scores_DT)

[0.77333333 0.93506494 0.86363636 0.94444444 0.8974359 ]


In [12]:
f1_scores_rf = cross_val_score(randomForest, OH_X_train, train_Y, scoring="f1", cv=5)
print(f1_scores_rf)

[0.84210526 0.94871795 0.91139241 0.95890411 0.92105263]


In [13]:
#smote

from imblearn.over_sampling import SMOTE

SMOTE = SMOTE()
smote_X, smote_Y = SMOTE.fit_resample(OH_X_train, train_Y)

f1_scores_mlp = cross_val_score(multiLayerPerceptron, smote_X, smote_Y, scoring="f1", cv=5)
print(f1_scores_mlp)

[0.85274018 0.98437912 0.94140766 0.96264842 0.98447778]


In [31]:
print(smote_Y.count(1))
print(smote_Y.count(0))

C:\Users\engel\AppData\Local\Temp\ipykernel_28664\3807120039.py:1: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. ser.count(level=1) should use ser.groupby(level=1).count().
  print(smote_Y.count(1))


ValueError: Series.count level is only valid with a MultiIndex

In [15]:
StringToClean = ["TransactionId", "BatchId","AccountId","SubscriptionId","CustomerId", "ProviderId", "ProductId", "ChannelId", "ProductCategory"]

# train[StringToClean].apply()

test_data = test.copy()
for col in StringToClean:
    test_data[col] = test_data[col].apply(lambda x : x.split("_")[-1])

test_data["TransactionStartDay"]  = test_data["TransactionStartTime"].apply(getDay)
test_data["TransactionStartTime"] = test_data["TransactionStartTime"].apply(getTime)
test_data = test_data.set_index("TransactionId")
test_data.drop(['CurrencyCode'], axis=1, inplace=True)
OH_encoder = OneHotEncoder(handle_unknown='ignore', sparse=False)
OH_cols_train = pd.DataFrame(OH_encoder.fit_transform(test_data["ProductCategory"].values.reshape(-1,1)))
OH_cols_train.rename(columns=lambda x: "ProductCategory_" + str(x), inplace=True)

# One-hot encoding removed index; put it back
OH_cols_train.index = test_data.index

# Remove categorical columns (will replace with one-hot encoding)
num_X_train = test_data.drop(["ProductCategory"], axis=1)

# Add one-hot encoded columns to numerical features
OH_X_train = pd.concat([num_X_train, OH_cols_train], axis=1)


OH_X_train.head()
# OH_X_train["TransactionStartTime"].head()

c:\Python310\lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


BatchId AccountId SubscriptionId CustomerId  CountryCode  \
TransactionId                                                            
50600           35028      2441           4426       2857          256   
95109           45139      3439           2643       3874          256   
47357           74887      4841           3829       2857          256   
28185           11025      2685           4626       3105          256   
22140           29804      4841           3829       3105          256   

              ProviderId ProductId ChannelId  Amount  Value  ...  \
TransactionId                                                ...   
50600                  5         3         3  1000.0   1000  ...   
95109                  5        15         3  2000.0   2000  ...   
47357                  4         6         2   -50.0     50  ...   
28185                  5        10         3  3000.0   3000  ...   
22140                  4         6         2   -60.0     60  ...   

               TransactionStartDay  ProductCategory_0  ProductCategory_1  \
TransactionId                                                              
50600                   20190213.0                1.0                0.0   
95109                   20190213.0                0.0                0.0   
47357                   20190213.0                0.0                0.0   
28185                   20190213.0                1.0                0.0   
22140                   20190213.0                0.0                0.0   

               ProductCategory_2  ProductCategory_3  ProductCategory_4  \
TransactionId                                                            
50600                        0.0                0.0                0.0   
95109                        0.0                0.0                0.0   
47357                        0.0                0.0                0.0   
28185                        0.0                0.0                0.0   
22140                        0.0                0.0                0.0   

               ProductCategory_5  ProductCategory_6  ProductCategory_7  \
TransactionId                                                            
50600                        0.0                0.0                0.0   
95109                        1.0                0.0                0.0   
47357                        1.0                0.0                0.0   
28185                        0.0                0.0                0.0   
22140                        1.0                0.0                0.0   

               ProductCategory_8  
TransactionId                     
50600                        0.0  
95109                        0.0  
47357                        0.0  
28185                        0.0  
22140                        0.0  

[5 rows x 22 columns]

In [44]:
multiLayerPerceptron.fit(smote_X, smote_Y)
test_res = multiLayerPerceptron.predict(OH_X_train)

In [32]:
decisionTree.fit(smote_X, smote_Y)
test_res = decisionTree.predict(OH_X_train)

In [34]:
randomForest.fit(smote_X, smote_Y)
test_res = randomForest.predict(OH_X_train)

In [42]:
#import xgboost
from xgboost import XGBClassifier
my_model = XGBClassifier(n_estimators=500)
#change dtype of all collumns to float
X = smote_X.astype('float32')
Y = smote_Y.astype('float32')
my_model.fit(X,Y)
test_res = my_model.predict(OH_X_train.astype('float32'))

In [47]:
a = my_model.predict(OH_X_train.astype('float32'))
b = multiLayerPerceptron.predict(OH_X_train)

print(np.unique(a, return_counts=True))
print(np.unique(b, return_counts=True))

(array([0, 1]), array([44939,    80], dtype=int64))
(array([0, 1], dtype=int64), array([44355,   664], dtype=int64))


In [45]:
print(test_res)

#concatenate the test result with coresponding transaction id
output = pd.DataFrame()
output["TransactionId"] = test["TransactionId"]
output["FraudResult"] = test_res
print(output.head(20))

#save the result to csv file
output.to_csv("submission.csv", index=False)

[0 0 0 ... 0 0 0]
           TransactionId  FraudResult
0    TransactionId_50600            0
1    TransactionId_95109            0
2    TransactionId_47357            0
3    TransactionId_28185            0
4    TransactionId_22140            0
5   TransactionId_134338            0
6   TransactionId_109096            0
7    TransactionId_14249            0
8    TransactionId_69896            0
9    TransactionId_91468            0
10   TransactionId_18862            0
11   TransactionId_29342            0
12  TransactionId_116873            0
13   TransactionId_81197            0
14   TransactionId_83120            0
15   TransactionId_40882            0
16   TransactionId_89297            0
17  TransactionId_112716            0
18   TransactionId_61794            0
19  TransactionId_124957            0
